/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (MacrossDoYouRememberLove)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x000703A0u
#define func_000703A0 BootEntry  /* alias */
